//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musicalog.Data
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlbumType", Namespace="http://schemas.datacontract.org/2004/07/Musicalog.Data")]
    public enum AlbumType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vinyl = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CD = 1,
    }
}
namespace Musicalog.API.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlbumDetailsModel", Namespace="http://schemas.datacontract.org/2004/07/Musicalog.API.Models")]
    public partial class AlbumDetailsModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArtistField;
        
        private string LabelField;
        
        private string NameField;
        
        private int StockField;
        
        private Musicalog.Data.AlbumType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist
        {
            get
            {
                return this.ArtistField;
            }
            set
            {
                this.ArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Musicalog.Data.AlbumType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAlbumService")]
public interface IAlbumService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlbumService/GetAlbums", ReplyAction="http://tempuri.org/IAlbumService/GetAlbumsResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Musicalog.Data.AlbumType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Musicalog.API.Models.AlbumDetailsModel))]
    object GetAlbums(int page, int take);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlbumService/GetAlbums", ReplyAction="http://tempuri.org/IAlbumService/GetAlbumsResponse")]
    System.Threading.Tasks.Task<object> GetAlbumsAsync(int page, int take);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlbumService/GetAlbum", ReplyAction="http://tempuri.org/IAlbumService/GetAlbumResponse")]
    Musicalog.API.Models.AlbumDetailsModel GetAlbum(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlbumService/GetAlbum", ReplyAction="http://tempuri.org/IAlbumService/GetAlbumResponse")]
    System.Threading.Tasks.Task<Musicalog.API.Models.AlbumDetailsModel> GetAlbumAsync(System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAlbumServiceChannel : IAlbumService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AlbumServiceClient : System.ServiceModel.ClientBase<IAlbumService>, IAlbumService
{
    
    public AlbumServiceClient()
    {
    }
    
    public AlbumServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AlbumServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlbumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AlbumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public object GetAlbums(int page, int take)
    {
        return base.Channel.GetAlbums(page, take);
    }
    
    public System.Threading.Tasks.Task<object> GetAlbumsAsync(int page, int take)
    {
        return base.Channel.GetAlbumsAsync(page, take);
    }
    
    public Musicalog.API.Models.AlbumDetailsModel GetAlbum(System.Guid id)
    {
        return base.Channel.GetAlbum(id);
    }
    
    public System.Threading.Tasks.Task<Musicalog.API.Models.AlbumDetailsModel> GetAlbumAsync(System.Guid id)
    {
        return base.Channel.GetAlbumAsync(id);
    }
}
